# Generated by Django 4.1.7 on 2023-02-19 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sarlovha', models.CharField(max_length=150)),
                ('Qisqacha_Matn', models.CharField(max_length=200)),
                ('Matn', models.TextField()),
                ('Rasm', models.ImageField(blank=True, upload_to='images/')),
                ('Vaqt', models.DateTimeField(auto_now_add=True)),
                ('Mualliff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
